#!/bin/bash

UNIQ=""
[ "$1" == "-u" ] && UNIQ="-u" && shift
[ $# -lt 2 ] && echo "Error: parameter missing. Usage: $0 [-u] <file1> <file2> [diff params]" 1>&2 && exit 1
FILE1="$1" && shift
FILE2="$1" && shift

diff $@ <(sort $UNIQ "$FILE1") <(sort $UNIQ "$FILE2")
