copy mingw64\bin\acountry.exe c:\xbin
copy mingw64\bin\adig.exe c:\xbin
copy mingw64\bin\ahost.exe c:\xbin
copy mingw64\bin\antiword.exe c:\xbin
copy mingw64\bin\blocked-file-util.exe c:\xbin
copy mingw64\bin\brotli.exe c:\xbin
copy mingw64\bin\bunzip2.exe c:\xbin
copy mingw64\bin\bzcat.exe c:\xbin
copy mingw64\bin\bzip2.exe c:\xbin
copy mingw64\bin\bzip2recover.exe c:\xbin
copy mingw64\bin\connect.exe c:\xbin
copy mingw64\bin\create-shortcut.exe c:\xbin
copy mingw64\bin\edit_test.exe c:\xbin
copy mingw64\bin\edit_test_dll.exe c:\xbin
copy mingw64\bin\envsubst.exe c:\xbin
copy mingw64\bin\gettext.exe c:\xbin
copy mingw64\bin\lzmadec.exe c:\xbin
copy mingw64\bin\lzmainfo.exe c:\xbin
copy mingw64\bin\odt2txt.exe c:\xbin
copy mingw64\bin\openssl.exe c:\xbin
copy mingw64\bin\p11-kit.exe c:\xbin
copy mingw64\bin\pdftotext.exe c:\xbin
copy mingw64\bin\pkcs1-conv.exe c:\xbin
copy mingw64\bin\proxy-lookup.exe c:\xbin
copy mingw64\bin\psl.exe c:\xbin
copy mingw64\bin\sexp-conv.exe c:\xbin
copy mingw64\bin\tclsh.exe c:\xbin
copy mingw64\bin\tclsh86.exe c:\xbin
copy mingw64\bin\trust.exe c:\xbin
copy mingw64\bin\unxz.exe c:\xbin
copy mingw64\bin\WhoUses.exe c:\xbin
copy mingw64\bin\wintoast.exe c:\xbin
copy mingw64\bin\wish.exe c:\xbin
copy mingw64\bin\wish86.exe c:\xbin
copy mingw64\bin\x86_64-w64-mingw32-agrep.exe c:\xbin
copy mingw64\bin\xmlwf.exe c:\xbin
copy mingw64\bin\xz.exe c:\xbin
copy mingw64\bin\xzcat.exe c:\xbin
copy mingw64\bin\xzdec.exe c:\xbin
copy usr\bin\arch.exe c:\xbin
copy usr\bin\awk.exe c:\xbin
copy usr\bin\b2sum.exe c:\xbin
copy usr\bin\base32.exe c:\xbin
copy usr\bin\base64.exe c:\xbin
copy usr\bin\basename.exe c:\xbin
copy usr\bin\basenc.exe c:\xbin
copy usr\bin\bash.exe c:\xbin
copy usr\bin\bunzip2.exe c:\xbin
copy usr\bin\bzcat.exe c:\xbin
copy usr\bin\bzip2.exe c:\xbin
copy usr\bin\bzip2recover.exe c:\xbin
copy usr\bin\captoinfo.exe c:\xbin
copy usr\bin\cat.exe c:\xbin
copy usr\bin\chattr.exe c:\xbin
copy usr\bin\chcon.exe c:\xbin
copy usr\bin\chgrp.exe c:\xbin
copy usr\bin\chmod.exe c:\xbin
copy usr\bin\chown.exe c:\xbin
copy usr\bin\chroot.exe c:\xbin
copy usr\bin\cksum.exe c:\xbin
copy usr\bin\clear.exe c:\xbin
copy usr\bin\cmp.exe c:\xbin
copy usr\bin\column.exe c:\xbin
copy usr\bin\comm.exe c:\xbin
copy usr\bin\cp.exe c:\xbin
copy usr\bin\csplit.exe c:\xbin
copy usr\bin\cut.exe c:\xbin
copy usr\bin\cygcheck.exe c:\xbin
copy usr\bin\cygpath.exe c:\xbin
copy usr\bin\cygwin-console-helper.exe c:\xbin
copy usr\bin\d2u.exe c:\xbin
copy usr\bin\dash.exe c:\xbin
copy usr\bin\dd.exe c:\xbin
copy usr\bin\df.exe c:\xbin
copy usr\bin\diff.exe c:\xbin
copy usr\bin\diff3.exe c:\xbin
copy usr\bin\dircolors.exe c:\xbin
copy usr\bin\dirmngr-client.exe c:\xbin
copy usr\bin\dirmngr.exe c:\xbin
copy usr\bin\dirname.exe c:\xbin
copy usr\bin\dos2unix.exe c:\xbin
copy usr\bin\du.exe c:\xbin
copy usr\bin\dumpsexp.exe c:\xbin
copy usr\bin\env.exe c:\xbin
copy usr\bin\envsubst.exe c:\xbin
copy usr\bin\ex.exe c:\xbin
copy usr\bin\expr.exe c:\xbin
copy usr\bin\factor.exe c:\xbin
copy usr\bin\false.exe c:\xbin
copy usr\bin\file.exe c:\xbin
copy usr\share\misc\magic.mgc c:\xbin\share
copy usr\bin\find.exe c:\xbin\xfind.exe
copy usr\bin\fmt.exe c:\xbin
copy usr\bin\fold.exe c:\xbin
copy usr\bin\funzip.exe c:\xbin
copy usr\bin\gawk-5.0.0.exe c:\xbin
copy usr\bin\gawk.exe c:\xbin
copy usr\bin\gencat.exe c:\xbin
copy usr\bin\getconf.exe c:\xbin
copy usr\bin\getfacl.exe c:\xbin
copy usr\bin\getopt.exe c:\xbin
copy usr\bin\gettext.exe c:\xbin
copy usr\bin\gkill.exe c:\xbin
copy usr\bin\gmondump.exe c:\xbin
copy usr\bin\gpg-agent.exe c:\xbin
copy usr\bin\gpg-connect-agent.exe c:\xbin
copy usr\bin\gpg-error.exe c:\xbin
copy usr\bin\gpg-wks-server.exe c:\xbin
copy usr\bin\gpg.exe c:\xbin
copy usr\bin\gpgconf.exe c:\xbin
copy usr\bin\gpgparsemail.exe c:\xbin
copy usr\bin\gpgscm.exe c:\xbin
copy usr\bin\gpgsm.exe c:\xbin
copy usr\bin\gpgsplit.exe c:\xbin
copy usr\bin\gpgtar.exe c:\xbin
copy usr\bin\gpgv.exe c:\xbin
copy usr\bin\grep.exe c:\xbin
copy usr\bin\groups.exe c:\xbin
copy usr\bin\gzip.exe c:\xbin
copy usr\bin\head.exe c:\xbin
copy usr\bin\hmac256.exe c:\xbin
copy usr\bin\hostid.exe c:\xbin
copy usr\bin\iconv.exe c:\xbin
copy usr\bin\id.exe c:\xbin
copy usr\bin\infocmp.exe c:\xbin
copy usr\bin\infotocap.exe c:\xbin
copy usr\bin\install.exe c:\xbin
copy usr\bin\join.exe c:\xbin
copy usr\bin\kbxutil.exe c:\xbin
copy usr\bin\kill.exe c:\xbin
copy usr\bin\ldd.exe c:\xbin
copy usr\bin\ldh.exe c:\xbin
copy usr\bin\less.exe c:\xbin
copy usr\bin\lessecho.exe c:\xbin
copy usr\bin\lesskey.exe c:\xbin
copy usr\bin\link.exe c:\xbin
copy usr\bin\ln.exe c:\xbin
copy usr\bin\locale.exe c:\xbin
copy usr\bin\locate.exe c:\xbin
copy usr\bin\logname.exe c:\xbin
copy usr\bin\ls.exe c:\xbin
copy usr\bin\lsattr.exe c:\xbin
copy usr\bin\mac2unix.exe c:\xbin
copy usr\bin\md5sum.exe c:\xbin
copy usr\bin\minidumper.exe c:\xbin
copy usr\bin\mintty.exe c:\xbin
copy usr\bin\mkfifo.exe c:\xbin
copy usr\bin\mkgroup.exe c:\xbin
copy usr\bin\mknod.exe c:\xbin
copy usr\bin\mkpasswd.exe c:\xbin
copy usr\bin\mktemp.exe c:\xbin
copy usr\bin\mount.exe c:\xbin
copy usr\bin\mpicalc.exe c:\xbin
copy usr\bin\msgattrib.exe c:\xbin
copy usr\bin\msgcat.exe c:\xbin
copy usr\bin\msgcmp.exe c:\xbin
copy usr\bin\msgcomm.exe c:\xbin
copy usr\bin\msgconv.exe c:\xbin
copy usr\bin\msgen.exe c:\xbin
copy usr\bin\msgexec.exe c:\xbin
copy usr\bin\msgfilter.exe c:\xbin
copy usr\bin\msgfmt.exe c:\xbin
copy usr\bin\msggrep.exe c:\xbin
copy usr\bin\msginit.exe c:\xbin
copy usr\bin\msgmerge.exe c:\xbin
copy usr\bin\msgunfmt.exe c:\xbin
copy usr\bin\msguniq.exe c:\xbin
copy usr\bin\mv.exe c:\xbin
copy usr\bin\nano.exe c:\xbin
copy usr\bin\nettle-hash.exe c:\xbin
copy usr\bin\nettle-lfib-stream.exe c:\xbin
copy usr\bin\nettle-pbkdf2.exe c:\xbin
copy usr\bin\ngettext.exe c:\xbin
copy usr\bin\nice.exe c:\xbin
copy usr\bin\nl.exe c:\xbin
copy usr\bin\nohup.exe c:\xbin
copy usr\bin\nproc.exe c:\xbin
copy usr\bin\numfmt.exe c:\xbin
copy usr\bin\od.exe c:\xbin
copy usr\bin\openssl.exe c:\xbin
copy usr\bin\p11-kit.exe c:\xbin
copy usr\bin\passwd.exe c:\xbin
copy usr\bin\paste.exe c:\xbin
copy usr\bin\patch.exe c:\xbin
copy usr\bin\pathchk.exe c:\xbin
copy usr\bin\perl.exe c:\xbin
copy usr\bin\perl5.36.1.exe c:\xbin
copy usr\bin\pinentry-w32.exe c:\xbin
copy usr\bin\pinentry.exe c:\xbin
copy usr\bin\pinky.exe c:\xbin
copy usr\bin\pkcs1-conv.exe c:\xbin
copy usr\bin\pldd.exe c:\xbin
copy usr\bin\pluginviewer.exe c:\xbin
copy usr\bin\pr.exe c:\xbin
copy usr\bin\printenv.exe c:\xbin
copy usr\bin\printf.exe c:\xbin
copy usr\bin\profiler.exe c:\xbin
copy usr\bin\ps.exe c:\xbin
copy usr\bin\psl.exe c:\xbin
copy usr\bin\ptx.exe c:\xbin
copy usr\bin\pwd.exe c:\xbin
copy usr\bin\readlink.exe c:\xbin
copy usr\bin\realpath.exe c:\xbin
copy usr\bin\rebase.exe c:\xbin
copy usr\bin\recode-sr-latin.exe c:\xbin
copy usr\bin\regtool.exe c:\xbin
copy usr\bin\rm.exe c:\xbin
copy usr\bin\rnano.exe c:\xbin
copy usr\bin\runcon.exe c:\xbin
copy usr\bin\rview.exe c:\xbin
copy usr\bin\rvim.exe c:\xbin
copy usr\bin\scp.exe c:\xbin\xscp.exe
copy usr\bin\sdiff.exe c:\xbin
copy usr\bin\sed.exe c:\xbin
copy usr\bin\seq.exe c:\xbin
copy usr\bin\setfacl.exe c:\xbin
copy usr\bin\setmetamode.exe c:\xbin
copy usr\bin\sexp-conv.exe c:\xbin
copy usr\bin\sftp.exe c:\xbin\xsftp.exe
copy usr\bin\sh.exe c:\xbin
copy usr\bin\sha1sum.exe c:\xbin
copy usr\bin\sha224sum.exe c:\xbin
copy usr\bin\sha256sum.exe c:\xbin
copy usr\bin\sha384sum.exe c:\xbin
copy usr\bin\sha512sum.exe c:\xbin
copy usr\bin\shred.exe c:\xbin
copy usr\bin\shuf.exe c:\xbin
copy usr\bin\sleep.exe c:\xbin
copy usr\bin\sort.exe c:\xbin\xsort.exe
copy usr\bin\split.exe c:\xbin
copy usr\bin\ssh.exe c:\xbin\xssh.exe
copy usr\bin\ssh-pageant.exe c:\xbin
copy usr\bin\sshd.exe c:\xbin
copy usr\bin\ssp.exe c:\xbin
copy usr\bin\stat.exe c:\xbin
copy usr\bin\stdbuf.exe c:\xbin
copy usr\bin\strace.exe c:\xbin
copy usr\bin\stty.exe c:\xbin
copy usr\bin\sum.exe c:\xbin
copy usr\bin\sync.exe c:\xbin
copy usr\bin\tabs.exe c:\xbin
copy usr\bin\tac.exe c:\xbin
copy usr\bin\tail.exe c:\xbin
copy usr\bin\tee.exe c:\xbin
copy usr\bin\test.exe c:\xbin
copy usr\bin\tic.exe c:\xbin
copy usr\bin\tig.exe c:\xbin
copy usr\bin\timeout.exe c:\xbin\xtimeout.exe
copy usr\bin\toe.exe c:\xbin
copy usr\bin\touch.exe c:\xbin
copy usr\bin\tput.exe c:\xbin
copy usr\bin\tr.exe c:\xbin
copy usr\bin\true.exe c:\xbin
copy usr\bin\truncate.exe c:\xbin
copy usr\bin\trust.exe c:\xbin
copy usr\bin\tset.exe c:\xbin
copy usr\bin\tsort.exe c:\xbin
copy usr\bin\tty.exe c:\xbin
copy usr\bin\tzset.exe c:\xbin
copy usr\bin\u2d.exe c:\xbin
copy usr\bin\umount.exe c:\xbin
copy usr\bin\uname.exe c:\xbin
copy usr\bin\unexpand.exe c:\xbin
copy usr\bin\uniq.exe c:\xbin
copy usr\bin\unix2dos.exe c:\xbin
copy usr\bin\unix2mac.exe c:\xbin
copy usr\bin\unlink.exe c:\xbin
copy usr\bin\unzip.exe c:\xbin
copy usr\bin\unzipsfx.exe c:\xbin
copy usr\bin\users.exe c:\xbin
copy usr\bin\vdir.exe c:\xbin
copy usr\bin\view.exe c:\xbin
copy usr\bin\vim.exe c:\xbin
copy usr\bin\vimdiff.exe c:\xbin
copy usr\bin\watchgnupg.exe c:\xbin
copy usr\bin\wc.exe c:\xbin
copy usr\bin\which.exe c:\xbin
copy usr\bin\who.exe c:\xbin
copy usr\bin\winpty-agent.exe c:\xbin
copy usr\bin\winpty-debugserver.exe c:\xbin
copy usr\bin\winpty.exe c:\xbin
copy usr\bin\xargs.exe c:\xbin
copy usr\bin\xgettext.exe c:\xbin
copy usr\bin\xxd.exe c:\xbin
copy usr\bin\yat2m.exe c:\xbin
copy usr\bin\yes.exe c:\xbin
copy usr\bin\zipinfo.exe c:\xbin
copy usr\bin\[.exe c:\xbin
copy mingw64\bin\edit.dll c:\xbin
copy mingw64\bin\libcares-2.dll c:\xbin
copy mingw64\bin\libexpat-1.dll c:\xbin
copy mingw64\bin\libgcc_s_seh-1.dll c:\xbin
copy mingw64\bin\libiconv-2.dll c:\xbin
copy mingw64\bin\libintl-8.dll c:\xbin
copy mingw64\bin\liblzma-5.dll c:\xbin
copy mingw64\bin\libpcre-1.dll c:\xbin
copy mingw64\bin\libpcreposix-0.dll c:\xbin
copy mingw64\bin\libstdc++-6.dll c:\xbin
copy mingw64\bin\libtre-5.dll c:\xbin
copy mingw64\bin\libwinpthread-1.dll c:\xbin
copy mingw64\bin\tcl86.dll c:\xbin
copy mingw64\bin\tk86.dll c:\xbin
copy mingw64\bin\zlib1.dll c:\xbin
copy usr\bin\msys-2.0.dll c:\xbin
copy usr\bin\msys-asn1-8.dll c:\xbin
copy usr\bin\msys-assuan-0.dll c:\xbin
copy usr\bin\msys-bz2-1.dll c:\xbin
copy usr\bin\msys-com_err-1.dll c:\xbin
copy usr\bin\msys-crypt-0.dll c:\xbin
copy usr\bin\msys-crypt-2.dll c:\xbin
copy usr\bin\msys-crypto-3.dll c:\xbin
copy usr\bin\msys-edit-0.dll c:\xbin
copy usr\bin\msys-ffi-8.dll c:\xbin
copy usr\bin\msys-gcc_s-seh-1.dll c:\xbin
copy usr\bin\msys-gcrypt-20.dll c:\xbin
copy usr\bin\msys-gettextlib-0-22.dll c:\xbin
copy usr\bin\msys-gettextsrc-0-22.dll c:\xbin
copy usr\bin\msys-gmp-10.dll c:\xbin
copy usr\bin\msys-gnutls-30.dll c:\xbin
copy usr\bin\msys-gpg-error-0.dll c:\xbin
copy usr\bin\msys-gssapi-3.dll c:\xbin
copy usr\bin\msys-hcrypto-4.dll c:\xbin
copy usr\bin\msys-heimbase-1.dll c:\xbin
copy usr\bin\msys-heimntlm-0.dll c:\xbin
copy usr\bin\msys-hogweed-6.dll c:\xbin
copy usr\bin\msys-hx509-5.dll c:\xbin
copy usr\bin\msys-iconv-2.dll c:\xbin
copy usr\bin\msys-idn2-0.dll c:\xbin
copy usr\bin\msys-intl-8.dll c:\xbin
copy usr\bin\msys-kafs-0.dll c:\xbin
copy usr\bin\msys-krb5-26.dll c:\xbin
copy usr\bin\msys-ksba-8.dll c:\xbin
copy usr\bin\msys-lzma-5.dll c:\xbin
copy usr\bin\msys-magic-1.dll c:\xbin
copy usr\bin\msys-mpfr-6.dll c:\xbin
copy usr\bin\msys-ncursesw6.dll c:\xbin
copy usr\bin\msys-nettle-8.dll c:\xbin
copy usr\bin\msys-npth-0.dll c:\xbin
copy usr\bin\msys-p11-kit-0.dll c:\xbin
copy usr\bin\msys-pcre-1.dll c:\xbin
copy usr\bin\msys-pcre2-8-0.dll c:\xbin
copy usr\bin\msys-pcre2-posix-3.dll c:\xbin
copy usr\bin\msys-perl5_36.dll c:\xbin
copy usr\bin\msys-psl-5.dll c:\xbin
copy usr\bin\msys-readline8.dll c:\xbin
copy usr\bin\msys-roken-18.dll c:\xbin
copy usr\bin\msys-sasl2-3.dll c:\xbin
copy usr\bin\msys-smartcols-1.dll c:\xbin
copy usr\bin\msys-sqlite3-0.dll c:\xbin
copy usr\bin\msys-ssl-3.dll c:\xbin
copy usr\bin\msys-tasn1-6.dll c:\xbin
copy usr\bin\msys-ticw6.dll c:\xbin
copy usr\bin\msys-unistring-5.dll c:\xbin
copy usr\bin\msys-wind-0.dll c:\xbin
copy usr\bin\msys-z.dll c:\xbin
copy usr\bin\msys-zstd-1.dll c:\xbin
copy usr\bin\winpty.dll c:\xbin
